### ISSUE TITLE
Dataset and code of use case chapter 02 missing

### ISSUE THREAD

**Issue by ccacheroc** [alod83/Data-Storytelling-with-Generative-AI-Using-Python-and-Altair#2]

**Comment by alod83** [comment]
Hi,
I have migrated the case studies into the directory CaseStudies. If you have found a reference to the use case of chapter 2 in the book, I would be grateful if you provided me with the page so I can update it. Thanks.

**Comment by ccacheroc** [comment]
Done. 
Thank you for your quick response! 
I am loving your book! 
Cheers!
Cris
